; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31332.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	scheme_entry
; Function compile flags: /Odtp
_TEXT	SEGMENT
scheme_entry PROC
; File c:\Users\User\src\compilers-there-n-back-again\src\ctest.c
; Line 2
	mov	eax, 7
; Line 3
	ret	0
scheme_entry ENDP
_TEXT	ENDS
END
